import { sha256 } from "@noble/hashes/sha2.js";
import { canonicalBytes } from "./canonical";
import {
  type ClearanceDigest,
  type DeploymentIntentDigest,
  type EvaluationInputsDigest,
  parseSha256Digest,
  type RobotBuildDigest,
  type SafetyEnvelopeCommitment,
  type Sha256Digest,
} from "./digest-values";
import { failProtocol } from "./errors";
import { parseSafetyEnvelopeId, parseSiteId } from "./identifiers";
import {
  PROTOCOL_VERSION,
  parseClearanceRecord,
  parseDeploymentIntent,
  parseEvaluationInputs,
  parseRobotBuildDescriptor,
  SAFETY_ENVELOPE_COMMITMENT_SCHEMA_VERSION,
} from "./schemas";

export const DIGEST_DOMAINS = Object.freeze({
  robotBuild: "preflight.digest.robot-build/v1",
  safetyEnvelopeCommitment: "preflight.digest.safety-envelope-commitment/v1",
  evaluationInputs: "preflight.digest.evaluation-inputs/v1",
  clearance: "preflight.digest.clearance/v1",
  deploymentIntent: "preflight.digest.deployment-intent/v1",
} as const);

type ProtocolDigest =
  | RobotBuildDigest
  | SafetyEnvelopeCommitment
  | EvaluationInputsDigest
  | ClearanceDigest
  | DeploymentIntentDigest;

function brandProtocolDigest<Digest extends ProtocolDigest>(digest: Sha256Digest): Digest {
  return digest as Digest;
}

function bytesToHex(bytes: Uint8Array): string {
  let output = "";
  for (const byte of bytes) output += byte.toString(16).padStart(2, "0");
  return output;
}

function digestFrame(domain: string, payload: unknown) {
  const frame = {
    domain,
    protocolVersion: PROTOCOL_VERSION,
    payload,
  };
  const encoded = canonicalBytes(frame);
  return parseSha256Digest(`sha256:${bytesToHex(sha256(encoded))}`);
}

export function digestRobotBuild(input: unknown): RobotBuildDigest {
  const descriptor = parseRobotBuildDescriptor(input);
  return brandProtocolDigest<RobotBuildDigest>(digestFrame(DIGEST_DOMAINS.robotBuild, descriptor));
}

/**
 * Commits to confidential envelope data without exposing it. The 32-byte blind must remain secret
 * from observers of the public commitment and should be generated by the later confidential path.
 */
export function digestSafetyEnvelopeCommitment(
  siteIdInput: unknown,
  safetyEnvelopeIdInput: unknown,
  confidentialPayload: unknown,
  blindingSecret: Uint8Array,
): SafetyEnvelopeCommitment {
  if (!(blindingSecret instanceof Uint8Array) || blindingSecret.length !== 32) {
    return failProtocol(
      "MALFORMED_OBJECT",
      "Safety-envelope commitments require a secret 32-byte blinding value",
      "blindingSecret",
    );
  }

  const payload = {
    schemaVersion: SAFETY_ENVELOPE_COMMITMENT_SCHEMA_VERSION,
    siteId: parseSiteId(siteIdInput),
    safetyEnvelopeId: parseSafetyEnvelopeId(safetyEnvelopeIdInput),
    confidentialPayload,
    blindingSecret: bytesToHex(blindingSecret),
  };
  return brandProtocolDigest<SafetyEnvelopeCommitment>(
    digestFrame(DIGEST_DOMAINS.safetyEnvelopeCommitment, payload),
  );
}

export function digestEvaluationInputs(input: unknown): EvaluationInputsDigest {
  const evaluationInputs = parseEvaluationInputs(input);
  return brandProtocolDigest<EvaluationInputsDigest>(
    digestFrame(DIGEST_DOMAINS.evaluationInputs, evaluationInputs),
  );
}

export function digestClearance(input: unknown): ClearanceDigest {
  const clearance = parseClearanceRecord(input);
  if (clearance.evaluationInputsDigest !== digestEvaluationInputs(clearance.inputs)) {
    return failProtocol(
      "DIGEST_MISMATCH",
      "Clearance evaluation-input digest does not match its bound inputs",
      "evaluationInputsDigest",
    );
  }
  return brandProtocolDigest<ClearanceDigest>(digestFrame(DIGEST_DOMAINS.clearance, clearance));
}

export function digestDeploymentIntent(input: unknown): DeploymentIntentDigest {
  const intent = parseDeploymentIntent(input);
  return brandProtocolDigest<DeploymentIntentDigest>(
    digestFrame(DIGEST_DOMAINS.deploymentIntent, intent),
  );
}
