import { sha256 } from "@noble/hashes/sha2.js";
import { canonicalBytes } from "./canonical";
import {
  isLegacyVersion,
  LEGACY_DIGEST_DOMAINS,
  LEGACY_PROTOCOL_VERSION,
  LEGACY_SCHEMA_VERSIONS,
} from "./compatibility";
import {
  type ClearanceDigest,
  type DeploymentIntentDigest,
  type EvaluationInputsDigest,
  parseSha256Digest,
  type RobotBuildDigest,
  type SafetyEnvelopeCommitment,
  type Sha256Digest,
} from "./digest-values";
import { failProtocol } from "./errors";
import { parseSafetyEnvelopeId, parseSiteId } from "./identifiers";
import {
  PROTOCOL_VERSION,
  parseClearanceRecord,
  parseDeploymentIntent,
  parseEvaluationInputs,
  parseRobotBuildDescriptor,
  SAFETY_ENVELOPE_COMMITMENT_SCHEMA_VERSION,
} from "./schemas";

export const DIGEST_DOMAINS = Object.freeze({
  robotBuild: "rovaulta.digest.robot-build/v1",
  safetyEnvelopeCommitment: "rovaulta.digest.safety-envelope-commitment/v1",
  evaluationInputs: "rovaulta.digest.evaluation-inputs/v1",
  clearance: "rovaulta.digest.clearance/v1",
  deploymentIntent: "rovaulta.digest.deployment-intent/v1",
} as const);

type ProtocolDigest =
  | RobotBuildDigest
  | SafetyEnvelopeCommitment
  | EvaluationInputsDigest
  | ClearanceDigest
  | DeploymentIntentDigest;

function brandProtocolDigest<Digest extends ProtocolDigest>(digest: Sha256Digest): Digest {
  return digest as Digest;
}

function bytesToHex(bytes: Uint8Array): string {
  let output = "";
  for (const byte of bytes) output += byte.toString(16).padStart(2, "0");
  return output;
}

function digestFrame(domain: string, protocolVersion: string, payload: unknown) {
  const frame = {
    domain,
    protocolVersion,
    payload,
  };
  const encoded = canonicalBytes(frame);
  return parseSha256Digest(`sha256:${bytesToHex(sha256(encoded))}`);
}

function digestDialect(input: { readonly schemaVersion?: unknown }): "current" | "legacy" {
  return isLegacyVersion(input.schemaVersion) ? "legacy" : "current";
}

function digestDomain(key: keyof typeof DIGEST_DOMAINS, dialect: "current" | "legacy"): string {
  return dialect === "legacy" ? LEGACY_DIGEST_DOMAINS[key] : DIGEST_DOMAINS[key];
}

function digestProtocolVersion(dialect: "current" | "legacy"): string {
  return dialect === "legacy" ? LEGACY_PROTOCOL_VERSION : PROTOCOL_VERSION;
}

export function digestRobotBuild(input: unknown): RobotBuildDigest {
  const descriptor = parseRobotBuildDescriptor(input);
  const dialect = digestDialect(descriptor);
  return brandProtocolDigest<RobotBuildDigest>(
    digestFrame(digestDomain("robotBuild", dialect), digestProtocolVersion(dialect), descriptor),
  );
}

/**
 * Commits to confidential envelope data without exposing it. The 32-byte blind must remain secret
 * from observers of the public commitment and should be generated by the later confidential path.
 */
export function digestSafetyEnvelopeCommitment(
  siteIdInput: unknown,
  safetyEnvelopeIdInput: unknown,
  confidentialPayload: unknown,
  blindingSecret: Uint8Array,
): SafetyEnvelopeCommitment {
  if (!(blindingSecret instanceof Uint8Array) || blindingSecret.length !== 32) {
    return failProtocol(
      "MALFORMED_OBJECT",
      "Safety-envelope commitments require a secret 32-byte blinding value",
      "blindingSecret",
    );
  }

  const payload = {
    schemaVersion: isLegacyVersion(
      (confidentialPayload as { readonly schemaVersion?: unknown })?.schemaVersion,
    )
      ? LEGACY_SCHEMA_VERSIONS.safetyEnvelopeCommitment
      : SAFETY_ENVELOPE_COMMITMENT_SCHEMA_VERSION,
    siteId: parseSiteId(siteIdInput),
    safetyEnvelopeId: parseSafetyEnvelopeId(safetyEnvelopeIdInput),
    confidentialPayload,
    blindingSecret: bytesToHex(blindingSecret),
  };
  const dialect = isLegacyVersion(payload.schemaVersion) ? "legacy" : "current";
  return brandProtocolDigest<SafetyEnvelopeCommitment>(
    digestFrame(
      digestDomain("safetyEnvelopeCommitment", dialect),
      digestProtocolVersion(dialect),
      payload,
    ),
  );
}

export function digestEvaluationInputs(input: unknown): EvaluationInputsDigest {
  const evaluationInputs = parseEvaluationInputs(input);
  const dialect = digestDialect(evaluationInputs);
  return brandProtocolDigest<EvaluationInputsDigest>(
    digestFrame(
      digestDomain("evaluationInputs", dialect),
      digestProtocolVersion(dialect),
      evaluationInputs,
    ),
  );
}

export function digestClearance(input: unknown): ClearanceDigest {
  const clearance = parseClearanceRecord(input);
  if (clearance.evaluationInputsDigest !== digestEvaluationInputs(clearance.inputs)) {
    return failProtocol(
      "DIGEST_MISMATCH",
      "Clearance evaluation-input digest does not match its bound inputs",
      "evaluationInputsDigest",
    );
  }
  const dialect = digestDialect(clearance);
  return brandProtocolDigest<ClearanceDigest>(
    digestFrame(digestDomain("clearance", dialect), digestProtocolVersion(dialect), clearance),
  );
}

export function digestDeploymentIntent(input: unknown): DeploymentIntentDigest {
  const intent = parseDeploymentIntent(input);
  const dialect = digestDialect(intent);
  return brandProtocolDigest<DeploymentIntentDigest>(
    digestFrame(digestDomain("deploymentIntent", dialect), digestProtocolVersion(dialect), intent),
  );
}
